version: "3.7"

services:
  ignition-sdk:
    image: inductiveautomation/ignition:latest
    container_name: ignition-sdk
    ports:
      - "8088:8088"  # Gateway web interface
      - "8043:8043"  # SSL (optional)
    volumes:
      # Use the named volume you declared below, so that on first startup
      # the container’s init script can copy in its default gateway.xml_clean → gateway.xml
      - ignition-sdk-data:/usr/local/bin/ignition/data

      # Then overlay *just* your custom ignition.conf (read-only)
      - ./ignition.conf:/usr/local/bin/ignition/data/ignition.conf:ro

    environment:
      GATEWAY_ADMIN_USERNAME: admin
      GATEWAY_ADMIN_PASSWORD: password
      ACCEPT_IGNITION_EULA: "Y"

volumes:
  ignition-sdk-data:
